#!/bin/bash

CURDIR=`pwd`
TESTAPP="$1"
TESTAPPL=`echo ${TESTAPP} | tr [:upper:] [:lower:]`
APPFOLDER="${CURDIR}/ta_${TESTAPPL}"
TEMPLATES="${CURDIR}/ta_template"

help() {
  echo "Usage: `basename $0` <DuiClassName>"
  exit 1
}

if [ "${TESTAPP}x" == "x" ]; then
    help
fi

if [ $# != 1 ]; then 
    help    
fi

if [ ! -d ${TEMPLATES} ]; then
  echo "No templates available, executing in wrong directory ?"
  exit
fi

if [ -d ${APPFOLDER} ]; then
  echo "${APPFOLDER} already exists, too risky to override"
  exit
fi

echo Creating a new folder ${APPFOLDER}
mkdir -p ${APPFOLDER}

pushd ${TEMPLATES} >/dev/null
for f in `find . -type f -print`; do
    DIRPART=`dirname $f`
    FILEPART=`basename $f`
    NEWFILEPART=`echo ${FILEPART} | sed -e 's/ta_template/'ta_${TESTAPPL}'/'`
    if [ ! -d "${APPFOLDER}/${DIRPART}" ]; then
        mkdir -p "${APPFOLDER}/${DIRPART}"
    fi
    SRC=${DIRPART}/${FILEPART}
    DST=${APPFOLDER}/${DIRPART}/${NEWFILEPART}
    sed -e 's/ta_template/ta_'${TESTAPPL}'/' \
        -e 's/MkTaClassName/'${TESTAPP}'/' \
        -e 's/mktaclassname/'${TESTAPPL}'/'  < ${SRC} > ${DST}
done
popd >/dev/null
