#!/bin/bash

CURDIR=`pwd`
TESTSUITE="$1"
TESTSUITEL=`echo ${TESTSUITE} | tr [:upper:] [:lower:]`
SUITEFOLDER="${CURDIR}/$TESTSUITE"
TEMPLATES="${CURDIR}/template"

help() {
    echo "Usage: `basename $0` <TestSuite>"
    exit 1
}

if [ "${TESTSUITE}x" == "x" ]; then
    help
fi

if [ $# != 1 ]; then
    help
fi

if [ ! -d ${TEMPLATES} ]; then
    echo "No templates available, executing in wrong directory ?"
    exit
fi

if [ -d ${SUITEFOLDER} ]; then
    echo "${SUITEFOLDER} already exists, too risky to overwrite"
    exit
fi

mkdir -p ${SUITEFOLDER}
echo Creating a new folder ${SUITEFOLDER}

cd ${TEMPLATES}
for f in `find . -type f -print`; do
    DIRPART=`dirname $f`
    FILEPART=`basename $f`
    NEWFILEPART=`echo ${FILEPART} | sed -e 's/suitename/'${TESTSUITEL}'/' -e 's/SuiteName/'${TESTSUITE}'/'`
    if [ ! -d "${SUITEFOLDER}/${DIRPART}" ]; then
        mkdir -p "${SUITEFOLDER}/${DIRPART}"
    fi
    SRC=${DIRPART}/${FILEPART}
    DST=${SUITEFOLDER}/${DIRPART}/${NEWFILEPART}
    sed -e 's/suitename/'${TESTSUITEL}'/' \
        -e 's/SuiteName/'${TESTSUITE}'/' < ${SRC} > ${DST}
done
cd ${CURDIR}
