#!/bin/sh

if [ $# != 3 ]
then
  echo "USAGE: createshortcut SHORTCUT THUMBNAIL TITLE" >&2
  exit 0
fi

# Get the absolute path of the shortcut
cd `dirname "${1}"`
SHORTCUT="`pwd`/`basename \"${1}\"`"
cd - >/dev/null

# Get the absolute path of the thumbnail
cd `dirname "${2}"`
THUMBNAIL="`pwd`/`basename \"${2}\"`"
cd - >/dev/null

# Insert an image file instance
tracker-sparql -u -q 'INSERT { <file://${SHORTCUT}> a nfo:FileDataObject, nfo:Image.}'

# Create the desktop bookmark for it
# _:x means "here is a URI that i dont care"
tracker-sparql -u -q "
INSERT {
  <maemo:DesktopBookmarkFolder> nfo:containsBookmark _:x .
  _:x a nfo:Bookmark ;
      nfo:bookmarks <file://${SHORTCUT}> ;
      maemo:bookmarkThumbnail
                \"file://${THUMBNAIL}\" ;
      nie:title \"${3}\" .
}"

